export default [
    {id: 0, title: 'Exercise 1', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo', img: 'https://images.pexels.com/photos/4058411/pexels-photo-4058411.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'},
    {id: 1, title: 'Exercise 2', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/2294354/pexels-photo-2294354.jpeg?cs=srgb&dl=pexels-li-sun-2294354.jpg&fm=jpg'},
    {id: 2, title: 'Exercise 3', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/841131/pexels-photo-841131.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'},
    {id: 3, title: 'Exercise 4', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/4058411/pexels-photo-4058411.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'},
    {id: 4, title: 'Exercise 5', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/2294354/pexels-photo-2294354.jpeg?cs=srgb&dl=pexels-li-sun-2294354.jpg&fm=jpg'},
    {id: 5, title: 'Exercise 6', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/841131/pexels-photo-841131.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'},
    {id: 6, title: 'Exercise 7', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/4058411/pexels-photo-4058411.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'},
    {id: 7, title: 'Exercise 8', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo', img: 'https://images.pexels.com/photos/4058411/pexels-photo-4058411.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'},
    {id: 8, title: 'Exercise 9', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/2294354/pexels-photo-2294354.jpeg?cs=srgb&dl=pexels-li-sun-2294354.jpg&fm=jpg'},
    {id: 9, title: 'Exercise 10', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/841131/pexels-photo-841131.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'},
    {id: 10, title: 'Exercise 11', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/4058411/pexels-photo-4058411.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'},
    {id: 11, title: 'Exercise 12', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/2294354/pexels-photo-2294354.jpeg?cs=srgb&dl=pexels-li-sun-2294354.jpg&fm=jpg'},
    {id: 12, title: 'Exercise 13', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/841131/pexels-photo-841131.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'},
    {id: 13, title: 'Exercise 14', desc: 'This is an exercise', instructions: 'Jump! Run! Cry!', type: 'Pre-training',
        author: 'Mr Musculo',  img: 'https://images.pexels.com/photos/4058411/pexels-photo-4058411.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'}
]